### ISSUE TITLE
Put inertia back into ship movement

### ISSUE THREAD

**Issue by Aeneas137** [Aeneas137/starflight-tlc#19]
Change it back to how it used to be with thrust/inertia but still cause the ship to slow down (a bit more slowly than at present). 
Yes, in space inertia does not stop, but it's a video game. Having to hold thrust continually is kind of fake. We were going with the Genesis version with that change where you have to hold down the thrust. It's okay  that way, but make the ship move a little easier and cruise a bit before slowing. At present, the ship stops  @abruptly.

**Comment by Corona688** [comment]
This must be a bug, as the game DOES NOT give you enough fuel to complete the demo journey -- not unless you grind every step of the way and are very VERY lucky.  PLEASE FIX!
