### ISSUE TITLE
Pirate encounters are too hard

### ISSUE THREAD

**Issue by Aeneas137** [Aeneas137/starflight-tlc#20]
Pirates are insanely hard!! There should always be just 1 ship per pirate encounter, not a fleet, and they shouldn't be so hard. 
Make pirates encounter the player OFTEN. It's too rare of an event. Just make them easy to kill. This will encourage the player to upgrade their ship but not frustrate them too much.

**Comment by swirsz** [comment]
Addressed with changes to ModuleInterstellarTravel.cpp - starting with line 716:

If the player has equipment with an average_class <= 4, the number of ships they will see is based on their average equipment class.  (Class 2 = 2 ships, etc.)

If their equipment is very good, then 70% of the time they will receive small fleets, 30% of time they will receive large fleets.  (actual numbers depend on each alien race)  I've toned down the numbers for pirate encounters so fully equipped players will still only see fleets of 1-3, or 5-10.
