### ISSUE TITLE
Ship combat improvement

### ISSUE THREAD

**Issue by Aeneas137** [Aeneas137/starflight-tlc#21]
Bring the action in closer. Right now, you get hosed with weapons fire and have to fly away and never see the alien ships. Reduce the range of all weapons and possibly reduce speed if that will help with gameplay. Make it so the player sees enemy ships more clearly. To that end, change the GUI during combat to reveal more of the screen.

**Comment by swirsz** [comment]
[F] keypress during combat minimizes (toggles) all GUI elements except for a minimalistic radar and the thin top status bar.
