### ISSUE TITLE
Log Planet feature

### ISSUE THREAD

**Issue by Aeneas137** [Aeneas137/starflight-tlc#3]
In the ControlPanel, the artwork and stubbed code still exists for Log Planet. That is a fun thing for players, esp old fans, and a quick way to make money (or get fined). Maybe reinstate this feature.

**Comment by johnweven** [comment]
I would really love to see the log planet feature be in the game. Hopefully we can implement such a thing.

**Comment by Blakeley00** [comment]
Same!
